FROM node:8.11.1-alpine

LABEL maintainer="yashsharma205@gmail.com"
ENV PORT 8080
RUN npm install --quiet -g pm2

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copies the local package.json file to the container
# and utilities docker container cache to not needing to rebuild
# and install node_modules/ everytime we build the docker, but only
# when the local package.json file changes.
# Install npm packages
COPY package.json /usr/src/app/
RUN npm install --production --quiet

COPY . /usr/src/app
EXPOSE 8080
CMD ["npm", "start"]