version: 2
jobs:
  build:
    working_directory: /usr/src/app
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose --file docker-compose-production.yml up -d

      - deploy:
          name: Push application Docker image
          branch: circle-ci
          region: us-east-1
          command: |
            - ./deploy.sh