machine:
  environment:
    PATH: "$PATH:~/$CIRCLE_PROJECT_REPONAME/bin"
  node:
    version: 8.9.3
  services:
    - docker
dependencies:
  post:
    - curl -L -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc1/jq-linux-x86_64-static && chmod +x ~/bin/jq
    - curl -L https://github.com/docker/compose/releases/download/1.5.0/docker-compose-`uname -s`-`uname -m` > ../bin/docker-compose && chmod +x ../bin/docker-compose
    - docker build --rm=false -t bellkev/circle-ecs:$CIRCLE_SHA1 . | cat # workaround progress weirdness
deployment:
  prod:
    branch: circle-ci
    commands:
      - ./deploy.sh